version: "3.8"
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  server:
    image: python:3.11-slim
    working_dir: /app/server
    volumes:
      - ./server:/app/server
    environment:
      - MONGO_URL=${MONGO_URL:-mongodb://mongo:27017/uyirkappan}
      - JWT_SECRET=${JWT_SECRET:-devsecret}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:5173}
      - SOCKET_CORS_ORIGINS=${SOCKET_CORS_ORIGINS:-http://localhost:5173}
      - OSRM_BASE=${OSRM_BASE:-https://router.project-osrm.org}
      - DEBUG_NO_AUTH=${DEBUG_NO_AUTH:-true}
    command: bash -lc "pip install -r requirements.txt && python app.py"
    depends_on:
      - mongo
    ports:
      - "5001:5001"
volumes:
  mongo_data:
